services:
  mongo:
    image: mongo:6
    command: --replSet "rs0"
    hostname: mongo
    volumes:
      - ./mongo/entrypoint.sh:/entrypoint.sh:ro,Z
      - db:/data/db
    entrypoint: /usr/bin/env bash /entrypoint.sh
  redis:
    image: redis:7
  account:
    image: pretendonetwork/account
    build: ./account
    restart: unless-stopped
    environment:
      GENERATE_NEW_KEYS: "true"
    volumes:
      - ./account_config.json:/app/config.json:ro,Z
      - certs:/app/certs
      - cdn:/cdn
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro,Z
      - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro,Z
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,Z
    ports:
      - 80:80
      - 443:443
    depends_on:
      - account

volumes:
  db:
  cdn:
  certs:
